apiVersion: apps/v1
kind: Deployment
metadata:
  name: discount-api
  labels:
    app: discount-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: discount-api
  template:
    metadata:
      labels:
        app: discount-api
    spec:
      containers:
      - name: discount-api
        image: discount-api:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "300m"
            memory: "256Mi"
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: "Development"
        - name: ASPNETCORE_URLS
          value: "http://+:8080"
        - name: ConnectionStrings__PostgreSQL
          value: "Host=host.docker.internal;Port=5432;Database=discountdb;Username=admin;Password=Password12*"
        - name: IdentityServerURL
          value: "http://identityserver:8080"
---
apiVersion: v1
kind: Service
metadata:
  name: discount-api
spec:
  type: NodePort
  selector:
    app: discount-api
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30014
